### PR TITLE
#76 Fixes for auto-position based on percentage.

### LINKED ISSUE #76: Automatic blind: writing to 'position' causes full up or full down
Using blind type 1 (Roller Blinds or Shutters) when setting `position` object so as to cause a change (ie. change 0% to 50%), the blind starts to move in the correct direction but does not stop at all. That is, it passes straight by the desired position to either fully open or fully closed.

So neither of these conditions could have been met (either that or the processing is *really* slow)...

```JS
                        if (isGoingDown && value >= targetValue) {
                            this.removeStateEventHandler(control.states.position, listenerName);
                            this.sendCommand(control.uuidAction, 'DownOff');
                        } else if (!isGoingDown && value <= targetValue) {
                            this.removeStateEventHandler(control.states.position, listenerName);
                            this.sendCommand(control.uuidAction, 'UpOff');
                        }
```

... which leads to the thought that if this is happening the state event handler is probably never getting cancelled which can't be good!

### PR DESCRIPTION
**Pull request by raintonr**
Fixes #76.

### CODE REVIEW

File: src/controls/Jalousie.ts [hunk 1]
```diff
@@ -3,6 +3,25 @@ import { Control } from '../structure-file';
 import { ControlBase, ControlType } from './control-base';
 
 export class Jalousie extends ControlBase {
+    protected positionTarget: number | undefined;
```
Comment (UncleSamSwiss) [inline src/controls/Jalousie.ts:6]: Is there a reason for using "protected"? if you don't have subclasses, I prefer "private". 
Same below.

File: src/controls/Jalousie.ts [hunk 2]
```diff
@@ -3,6 +3,25 @@ import { Control } from '../structure-file';
...
+    // The upDownChangeHandler callback will be triggered when any movement starts or stops.
+    // Normally we want upDownChangeHandler to clear any target as it signifies manual command
+    // has occurred. This can happen in normal use or before a target has been reached for
+    // example.
+    // But in the case of movement started as a result of an auto-position command, we don't
+    // want to clear that target.
+    // For this reason we have the below boolean that tells upDownChangeHandler to ignore the
+    // first change it sees after an auto-position command is started.
+    protected upDownAutoCommandHandled: boolean | undefined;
+    protected async upDownChangeHandler(): Promise<void> {
```
Comment (UncleSamSwiss) [inline src/controls/Jalousie.ts:17]: Please move the handler below the loadAsync(). The method loadAsync() should always be the first method in the control handler classes.

File: src/controls/Jalousie.ts [hunk 3]
```diff
@@ -27,9 +46,13 @@ export class Jalousie extends ControlBase {
         await this.createBooleanControlStateObjectAsync(control.name, uuid, control.states, 'up', 'indicator', {
             write: true,
         });
+        this.addStateEventHandler(control.states.up, this.upDownChangeHandler.bind(this), 'up');
```
Comment (UncleSamSwiss) [inline src/controls/Jalousie.ts:49]: I know, `bind()` is used a lot in JavaScript, but it is ugly IMHO.

Please simply use an arrow function like so:
```js
this.addStateEventHandler(control.states.up, () => this.upDownChangeHandler(), 'up');
````

Same below.

File: src/controls/Jalousie.ts [hunk 4]
```diff
@@ -41,6 +64,30 @@ export class Jalousie extends ControlBase {
                 // TODO: re-add: smartIgnore: false
             },
         );
+        this.addStateEventHandler(
```
Comment (UncleSamSwiss) [inline src/controls/Jalousie.ts:67]: Please move this call inside the `if (control.states.position) {` below.
I don't remember the reason for that "if", but since it is there, we must assume there are situations where `control.states.position` is not set.

File: src/controls/Jalousie.ts [hunk 5]
```diff
@@ -3,6 +3,25 @@ import { Control } from '../structure-file';
...
+
+    // The upDownChangeHandler callback will be triggered when any movement starts or stops.
+    // Normally we want upDownChangeHandler to clear any target as it signifies manual command
+    // has occurred. This can happen in normal use or before a target has been reached for
+    // example.
+    // But in the case of movement started as a result of an auto-position command, we don't
+    // want to clear that target.
+    // For this reason we have the below boolean that tells upDownChangeHandler to ignore the
+    // first change it sees after an auto-position command is started.
+    protected upDownAutoCommandHandled: boolean | undefined;
```
Comment (UncleSamSwiss) [inline src/controls/Jalousie.ts:16]: Is there a reason for having "`| undefined`"?
I would prefer:
```js
upDownAutoCommandHandled = false;
```
If you want, you can still provide the type, but it is automatically deduced from the assignment.

File: src/controls/Jalousie.ts [hunk 6]
```diff
@@ -41,6 +64,30 @@ export class Jalousie extends ControlBase {
...
+            control.states.position,
+            async (value: any) => {
+                if (typeof this.positionTarget === 'number') {
+                    // Below, the actual command ('up' or 'down') is irrelevant but we
+                    // need to know the direction for target test.
+                    if (this.positionTarget > 0) {
+                        // Going down
+                        if (value >= this.positionTarget) {
+                            this.positionTarget = undefined;
+                            await this.sendCommand(control.uuidAction, 'down');
```
Comment (UncleSamSwiss) [inline src/controls/Jalousie.ts:77]: Is there a reason for using "down" instead of "DownOff" as in the original code?
Same below for "up" vs. "UpOff".

**Review by UncleSamSwiss — CHANGES_REQUESTED** [review]
Thanks for your PR. Sorry it took me so long to review it.

**Comment by UncleSamSwiss** [comment]
One more thing: please also update the Readme ("Supported Control Types" and "Changelog")

**Comment by raintonr** [comment]
> One more thing: please also update the Readme ("Supported Control Types" and "Changelog")

Duplicate of https://github.com/UncleSamSwiss/ioBroker.loxone/pull/78#issuecomment-788734130 right?

File: src/controls/Jalousie.ts (hunk 1 above)
Comment (raintonr) [reply src/controls/Jalousie.ts:6]: OK

File: src/controls/Jalousie.ts (hunk 3 above)
Comment (raintonr) [reply src/controls/Jalousie.ts:49]: Well, neither notation is particularly elegant and I actually prefer the `bind`, but as you wish.

File: src/controls/Jalousie.ts (hunk 5 above)
Comment (raintonr) [reply src/controls/Jalousie.ts:16]: Fair enough.

File: src/controls/Jalousie.ts (hunk 2 above)
Comment (raintonr) [reply src/controls/Jalousie.ts:17]: It doesn't matter, but as you wish.

File: src/controls/Jalousie.ts (hunk 4 above)
Comment (raintonr) [reply src/controls/Jalousie.ts:67]: OK.

File: src/controls/Jalousie.ts (hunk 6 above)
Comment (raintonr) [reply src/controls/Jalousie.ts:77]: Yes. `DownOff` and `UpOff` actually cause direction to reverse a little. Sending `up` or `down` just stops as it should.

**Comment by UncleSamSwiss** [comment]
> > One more thing: please also update the Readme ("Supported Control Types" and "Changelog")
> 
> Duplicate of [#78 (comment)](https://github.com/UncleSamSwiss/ioBroker.loxone/pull/78#issuecomment-788734130) right?

No, at least the Changelog should contain a reference your fixes.
I guess nothing changed in this section: https://github.com/UncleSamSwiss/ioBroker.loxone#jalousie ?

**Review by UncleSamSwiss — APPROVED** [review]
Thanks for your fixes.
